version: '3'

services:

  ### MySQL ################################################
  mysql:
    build:
      context: ./build/docker/mysql
      args:
        - MYSQL_VERSION=5.7
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./docker/docker-runtime/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "33060:3306"
    logging:
      options:
        max-file: "5"
        max-size: "10m"


  ### Redis ################################################
  redis:
    image: redis:latest
    volumes:
      - ./build/docker/docker-runtime/redis:/data
    ports:
      - "6379:6379"
    logging:
      options:
        max-file: "5"
        max-size: "10m"
